local g = require "main.globals"
local U = require "main.utilities"

function on_input(self, action_id, action)
	if (action.x) then U.button_hover_effects(self, action, self.buttons) end -- so that buttons don't try to call on button presses, for example
	if action_id == hash("touch") and action.released then
		if gui.pick_node(gui.get_node("discord"), action.x, action.y) then
			sys.open_url("https://discord.gg/gQgmYMM9A9", {target = "_blank"})
		end
	end
end


function init(self)
	msg.post(".", "acquire_input_focus")
	gui.set_color(gui.get_node("background"), g.dark_purple)
	gui.set_color(gui.get_node("miat"), g.cerise)
	gui.animate(gui.get_node("thanks"), "color.w", 1, gui.EASING_INCUBIC, 0.3)
	gui.animate(gui.get_node("miat"), "color.w", 1, gui.EASING_INCUBIC, 1)
end