-- necessary to make FMOD run its own update cycle. Both Master and Master.strings banks are necessary to load

local fmod = require "fmod"
local states = require "main.states"

function update(self, dt)
	fmod.studio.system:update()
end


function init(self)
	if fmod then
		fmod.init()
		fmod.load_bank("Master")
		fmod.load_bank("Master.strings")
	end
	defos.set_cursor_visible(states.custom_cursor) -- hide system cursor
end
