

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.released then
		--do stuff
		if gui.pick_node(gui.get_node("reroll"), action.x, action.y) then
			msg.post("/buildings#building_facade", "reroll")
		end
	end
end

function init(self)
	msg.post(".", "acquire_input_focus")
	gui.animate(gui.get_node("fade-in"), "color.w", 0, gui.EASING_LINEAR, 0.2)
	self.buttons = {"to_menu"}
end
