local U = require "main.utilities"

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	if (action.x) then U.button_hover_effects(self, action, self.buttons) end -- so that buttons don't try to call on button presses, for example
	if action_id == hash("touch") and action.released then
		--do stuff
		if gui.pick_node(gui.get_node("reroll"), action.x, action.y) then
			msg.post("/buildings#building_facade", "reroll")
		end
	end
end

function init(self)
	msg.post(".", "acquire_input_focus")
	gui.animate(gui.get_node("fade-in"), "color.w", 0, gui.EASING_LINEAR, 0.2)
	self.buttons = {"to_menu"}
end
