local S = require "main.states"

local camera = require "orthographic.camera"
local CAMERA_ID = hash("/camera")


function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end


function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.released then
		--do stuff
	end
	if S.pause_keys[action_id] then
		if S.paused then 
			msg.post(".", "set_time_step", {factor = 0, mode = 0})
			S.paused = false
			msg.post("main:/GUI#main", "paused")
		elseif not S.paused then
			msg.post(".", "set_time_step", {factor = 1, mode = 0})
			S.paused = true
			msg.post("main:/GUI#main", "paused")
		end
	end
end



function init(self)
	msg.post(".", "acquire_input_focus")
	print("loading main")
end