local states = require "main.states"


local current_sound = "manager:/controller_audio#SFX_placeholder"
local currently_playing = {  }

local list = { "sound", "sound", "sound", "sound", "sound" }

local function sound_fading(target_sound)
	local fade_time = 0.3
	sound.play(target_sound, { gain = 0.0 })
	go.animate(target_sound, "gain", go.PLAYBACK_ONCE_FORWARD, 1, go.EASING_INCUBIC, fade_time)
	go.animate(current_sound, "gain", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_INCUBIC, fade_time, 0, function()
		sound.stop(current_sound)
	end)
	current_sound = target_sound
	table.insert(currently_playing, target_sound)
end

-- put all sounds that should stop at once in here
local function constant_sounds_playing(target_sound)
	sound.play(target_sound)
	table.insert(currently_playing, target_sound)
end


local function sound_once(target_sound)
	sound.stop(target_sound)
	timer.delay(0.1, false, function()sound.play(target_sound)end) -- delayed, so that the SFX cannot pile up
end

function on_message(self, message_id, message, sender)
-- click sound, playing everywhere all the time, called from manager
	if message_id == hash("play_click") then
		sound_once("manager:/controller_audio#SFX_placeholder")
	end
-- looping sounds (music + ambiance)
	if message_id == hash("play_music") then
		constant_sounds_playing("manager:/controller_audio#music_placeholder")
	elseif message_id == hash("stop_music") then
		sound.stop("manager:/controller_audio#music_placeholder")
	end
-- random sounds
	if message_id == hash("play_sound_from_list") then
		local random = list[math.random(1, #list)]
		sound.play("manager:/controller_audio#" .. random)
	end
-- stopping all sounds from list
	if message_id == hash("stop_music") then
		for _, track in ipairs(currently_playing) do
			sound.stop(track)
		end
	end
end

--[[
function init(self)
	-- Load banks - Master and Master Strings are always necessary, add optionals
	fmod.studio.system:load_bank_memory(resource.load("/audio/fmod/banks/Master.bank"), fmod.STUDIO_LOAD_BANK_NORMAL)
	fmod.studio.system:load_bank_memory(resource.load("/audio/fmod/banks/Master.strings.bank"), fmod.STUDIO_LOAD_BANK_NORMAL)
	fmod.studio.system:load_bank_memory(resource.load("/audio/fmod/banks/fill_in_name.bank"), fmod.STUDIO_LOAD_BANK_NORMAL)
	
end
]]