local camera = require "orthographic.camera"
local CAMERA_ID = hash("/camera")

function init(self)
	msg.post(".", "acquire_input_focus")
end


function on_input(self, action_id, action)
	if action_id == hash("click") then
		if action.pressed then
			self.pressed_pos = vmath.vector3(action.x, action.y, 0)
			self.camera_pos = go.get_position(CAMERA_ID)
		elseif action.released then
			self.pressed_pos = nil
		end
	elseif action_id == nil and self.pressed_pos then
		local zoom = camera.get_zoom(CAMERA_ID)
		local action_pos = vmath.vector3(action.x, action.y, 0)
		local camera_pos = self.camera_pos + (self.pressed_pos - action_pos) / zoom
		go.set_position(camera_pos, CAMERA_ID)
	end
end