local camera = require "orthographic.camera"
local CAMERA_ID = hash("/camera")

local proxies_loaded = {}

local function clean_proxy_loading()
	for i, proxy in ipairs(proxies_loaded) do
		msg.post(proxy, "unload")
	end
	proxies_loaded = {}
end



function on_message(self, message_id, message, sender)
	if message_id == hash("proxy_loaded") then
		table.insert(proxies_loaded, sender)
		msg.post(sender, "enable") --enable all proxies that are loaded
		msg.post(sender, "acquire_input_focus") --give focus to all loaded proxies; necessary to get drag + zoom to work
	end
	if message_id == hash("quit_pressed") then --quit button functionality
		sys.exit(0)
	elseif message_id == hash("start_pressed") then
		clean_proxy_loading()
		msg.post("#px_main", "load")
	elseif message_id == hash("load_startup") then
		clean_proxy_loading()
		msg.post("#px_startup", "load")
	end
end


function init(self)
	math.randomseed(os.time()) --random needs to be initialised
	msg.post(".", "acquire_input_focus")


	--msg.post("#px_studio", "load")
	--msg.post("#px_startup", "load")
	msg.post("#px_main", "load")
end